name: Run Java Test on Push or Manually

on:
  push:
  workflow_dispatch:

jobs:
  run-java-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn test

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: Test-Report
          path: GitHubActionsTest/target/surefire-reports/FirstPackage.MyManualTest.txt
