name: Run Java Test on Push or Manually

on:
  push:
  workflow_dispatch:

jobs:
  run-java-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug: Show folder structure
        run: dir
        shell: cmd

      - name: Debug: List folders recursively
        run: dir /s /b
        shell: cmd

      # 💡 Adjust this path if your Maven project is in a subfolder
      - name: Build and run tests
        run: mvn test
        working-directory: GitHubActionsTest

      - name: Debug: Show test output folder
        run: dir GitHubActionsTest\target\surefire-reports
        shell: cmd

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: GitHubActionsTest/target/surefire-reports/*.txt
