name: Run Java Test on Push or Manually

on:
  push:                # Run when code is pushed to any branch
  workflow_dispatch:   # Allow manual trigger via GitHub UI

jobs:
  run-java-tests:
    runs-on: windows-latest  # ✅ Official GitHub-hosted Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: mvn test
