name: On Pull Request
on: pull_request
    types: [opened, closed]
    
jobs:
    print PR info:
        runs-on: windows-latest
    steps:
     -name: print 'PR' info
      run: echo "PR raised or Closed"