name: On Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed]
    branches:
        -Dinesh-QA
    paths-ignore:
        -'.github/**'

jobs:
  print-pr-info:
    runs-on: windows-latest

    steps:
      - name: Print PR info
        run: echo "PR raised or Closed"
