name: Push Trigger job

on:
  push:
  paths-ignore:
    - '.github/**'

jobs:
  get-github-context:
    runs-on: windows-latest

    steps:
      - name: Print GitHub context
        run: echo '${{ toJSON(github) }}'
